name: Build & Publish Atc.XamlToolkit.Wpf

on:
  push:
    tags: [ 'Atc.XamlToolkit.Wpf@v*.*.*' ]

env:
  NUGET_REPO_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ›’ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_PAT }}

      - name: âš™ï¸ Setup dotnet 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ“ Ensure nuget.org added as package source on Windows
        run: dotnet nuget add source ${{ env.NUGET_REPO_URL }} -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config
        continue-on-error: true

      - name: ğŸ§¹ Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: ğŸ” Restore packages
        run: dotnet restore src/Atc.XamlToolkit.Wpf/Atc.XamlToolkit.Wpf.csproj

      - name: ğŸ› ï¸ Build SourceGenerators
        run: dotnet build src/Atc.XamlToolkit.SourceGenerators/Atc.XamlToolkit.SourceGenerators.csproj -c Release

      - name: ğŸ› ï¸ Build library in release mode
        run: dotnet build src/Atc.XamlToolkit.Wpf/Atc.XamlToolkit.Wpf.csproj -c Release --no-restore /p:UseSourceLink=true

      - name: ğŸ—³ï¸ Pack library for release
        run: dotnet pack src/Atc.XamlToolkit.Wpf/Atc.XamlToolkit.Wpf.csproj -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages /p:PublicRelease=true

      - name: ğŸ“¦ Push package to NuGet
        shell: pwsh
        run: |
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/Atc.XamlToolkit.Wpf*.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_REPO_URL }} --skip-duplicate --no-symbols
